### ISSUE TITLE
A marshalling test failed on my Arch Linux.

### ISSUE THREAD

**Issue by eugeneai** [keriharris/plgi#1]
Hi, Keri!

I've tried to install locally package plgi on my PC in Arch Linux environment with the following packages.

local/swi-prolog-devel 7.7.1-2
extra/gtk3 3.22.24+90+g5ad9ecaff0-1
extra/gtk3-print-backends 3.22.24+90+g5ad9ecaff0-1 (gnome)
extra/gobject-introspection 1.54.1-1
extra/gobject-introspection-runtime 1.54.1-1

resulted in one failed test: 
% (process:2909): GLib-GObject-CRITICAL **: g_value_set_int: assertion 'G_VALUE_HOLDS_INT (value)' failed
% 
% ERROR: /home/eugeneai/lib/swipl/pack/plgi/test/marshaller_tests.pl:2055:
% 	test gi_marshalling_tests_gclosure_return: failed

I tried to figure out the cause, but failed too because i do not undesrstand logics behind. I sadely commented it out the test, and the package finaly installed.

5b81ca2461036857f75e2c2f226326f683248a02

So, if You point me the a documentstion on how to debug the test I could go further in the failured test investigation.

Best regards,
Evgeny

**Comment by keriharris** [comment]
Hi Evgeny

I recently fixed a bug in PLGI that deals with GValue objects being garbaged collected while they were still referenced in Prolog. I've just released v1.0.5 that contains this fix. Can you update your PLGI installation and see if that fixes the failing regression test.


Thanks

Keri

**Comment by eugeneai** [comment]
Hi, Keri!
I've tried to upgrade to 1.0.5. The test failed again. 

% (process:20027): GLib-GObject-CRITICAL **: g_value_set_int: assertion 'G_VALUE_HOLDS_INT (value)' failed
% 
% ERROR: /home/eugeneai/lib/swipl/pack/plgi/test/marshaller_tests.pl:2055:
% 	test gi_marshalling_tests_gclosure_return: failed
% 


Evgeny

**Comment by keriharris** [comment]
I've fixed this in plgi-1.0.6.

The failing test is caused by a change in the annotations around g_closure_invoke() in newer versions of glib. This annotation change means that the marshaller could no longer determine that the return value of g_closure_invoke() must be pass in as an instantiated GValue. The workaround was to implement our own wrapper around g_closure_invoke(). This bug has also affected over glib language bindings. e.g. https://github.com/pavouk/lgi/issues/132.

Thanks for reporting this!
